name: uhi-drivers-lausanne
channels:
  - conda-forge
  - bioconda
dependencies:
  - awscli
  - geopandas
  - ipykernel
  - papermill
  - pip
  - pre-commit
  - python=3.11
  - shapely
  - snakemake
  - tqdm
  - pip:
      - -e .
      - awscli-plugin-endpoint
